export { default as anonymos } from './anonymos.webp'
export { default as blank } from './blank.webp'
export { default as gammer } from './gammer.webp'
export { default as gamming } from './gamming.webp'
export { default as ninja } from './ninja.webp'
export { default as panda } from './panda.webp'